version: '2'

volumes:
  myshare:
    driver: local

services:

  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    # command: /gunicorn.sh
    # user: flask
    # depends_on:
    #   - postgres
    #   - redis
    env_file: prod.env
    environment:
    #   # - POSTGRES_USER=docker_ex
    - USE_DOCKER=yes
    #   - GOOGLE_APPS_API_KEY=test
    #   - flask_SECRET_KEY=somekeyfortesting
    volumes:
    - 'myshare:/app'

  nginx:
    build: ./compose/nginx
    depends_on:
      - flask
    volumes:
    - 'myshare:/app'
    ports:
      - "80:80"
      - "81:81"


